### ISSUE TITLE
CI versioning

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/relay#109]
![изображение](https://user-images.githubusercontent.com/21261007/117101928-e9ce5f00-ad7f-11eb-85b1-08523969cb91.png)

**Comment by Shane32** [comment]
Not sure how that happened.  I must have uploaded the file myself, since looking at the workflow artifacts it's evident that the CI script didn't generate that file, nor did it reach the step to upload the file as a release artifact.  I updated the release artifacts with the file generated from the workflow.
