### ISSUE TITLE
How to get schema.json file

### ISSUE THREAD

**Issue by MapleYe** [graphql-dotnet/relay#8]
I'd like to know how to create schema.json file. Thank you.

**Comment by jquense** [comment]
You need to build one, by running an introspection query against your schema and writing the result out. See https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay.Todo/SchemaWriter.cs

There isn't really a generic way to handle this tho because you need to actually construct your schema which may mean mocking out dependencies depending on your DI setup

**Comment by MapleYe** [comment]
Thanks for the answer. Currently I'm using get-graphql-schema to build the schema file for Relay Modern. As you said, that package fetches an introspection query from the GraphQL server.

**Comment by michal-ciechan** [comment]
I managed to get the schema file using graphql-cli.

See this SO answer: [Get GraphQL whole schema query](https://stackoverflow.com/a/42010467)

**Comment by sungam3r** [comment]
https://github.com/sungam3r/graphql-sdl-exporter
